$kind: http-request
name: create_task
url: "{{baseurl}}/tasks"
method: POST
body:
  type: json
  content: |-
    {
        "title": "поиграть в пк",
        "author_user_id": 2
    }
order: 66210033935
